### ISSUE TITLE
Nested sortable

### ISSUE THREAD

**Issue by minhtranite** [a5hik/ng-sortable#15]
Hi guys!
How to make 'ng-sortable' work with nested sortable or disable inner sortable.

**Comment by butaixianran** [comment]
Here is a solution, without angular-ui-tree.

Actually ng-sortable supports nested data very well, the problem is: as-sortable-item-handle don't.

So, the really problem is:  element with "as-sortable-item-handle" can't be the container of "as-sortable" and "as-sortable-item".

Then the solution is simple:
Set a title bar for all the nodes you want to drag. And set  as-sortable-item-handle on this title bar.
Like this:

```` html
<div this-is-level-1>
    <div>title bar</div>
    <div this-is-level-2>
        <div>title bar</div>
        <div this-is-level-3>
        </div>
    </div>
</div>
````

In this way, no matter how many levels your nested data has, your as-sortable and as-sortable-item will never be under an  "as-sortable-item-handle "
