### ISSUE TITLE
Dragging causing highlighting and other issues.

### ISSUE THREAD

**Issue by jacobphillipsfs** [a5hik/ng-sortable#165]
When I attempt to drag using ng-sortable it's causing me to highlight any text or space I cover. Also if I move an item and then select it again. The dragging does not work until I let go of the mouse. I then have to click in order to place the object. My app was working previously and seemed to change suddenly one day. I have not altered any code since it was working last. When using Simple Demo in the description I have the same problem. This occurs on Firefox, IE, and Chrome.
![image](https://cloud.githubusercontent.com/assets/12566271/7789950/c489424e-0238-11e5-8a89-cff5f446d03c.png)

**Comment by asperling** [comment]
:+1: 

Same here.

**Comment by asperling** [comment]
Well since I needed a quick fix I forked and fiddled. And I managed to fix it for my env. But there is no pull request since I still use 1.1.6 based on the dependency update to angular 1.3.x in 1.1.7 (which is IMO not too polite in a patch update). 

But first here is what I did: https://github.com/asperling/ng-sortable/commit/08fc51463cc410f3cc117cf0b7758e08795e534a
(remember its based on 1.1.6)

Maybe some time I'll get my app to work with angular 1.3.x and get some more testing and finally a pull request ready.

**Comment by marcjay** [comment]
Same here.

Had not made any code changes or updated any libraries (including this one). Seemed to coincide with a Chrome update to 43.0.2357.65m. 

Thank you @asperling, that patch works for me too

**Comment by asperling** [comment]
@marcjay No problem and you seem to be right, the problem seems to be related to that update. I restarted Chrome a minute ago for - as it seems - another update (Version 43.0.2357.81) and magically the bug is gone (without my "patch"). For both my app and the demo which had the same problem.

Can anybody confirm? If so this could be closed.

**Comment by jacobphillipsfs** [comment]
My app is working again, however the simple demo is still broken. I'll go ahead and close this. Another issue can be started if needed.

**Comment by marcjay** [comment]
Also working for me with .81 - both my app and the simple demo no longer have the issue
