### ISSUE TITLE
Sortable overriding values

### ISSUE THREAD

**Issue by ajmajma** [a5hik/ng-sortable#171]
Hi. I have 2 lists, when I drag from one list to another it works great, however when  I try to then re-order that list it seems to overwrite the items i dragged over with ones that were already in current list when I move them. Thanks!

**Comment by ajmajma** [comment]
Also - I am using track by $index on my repeats because of how my data looks. Is possible this is effecting it?

**Comment by JPorry** [comment]
Hello!

I think your issue is not related to this plugin, it is related with the fact that you are tracking by the index, and every time you remove an item from a list, the index of the elements change, creating a huge mess as you can see.
The best solution that I have found for this so far is to have a unique id in every item in the list and use that in the 'track by'.

Here you have the modified version of the example so you can see what I am saying, and everything seems to work fine. In this version each item has it's own Id (list1_1, list1_2, list2_1... and so on) and we use that property in the 'track by'

http://plnkr.co/edit/qhItCInWUzz4sdEdddAx?p=preview 

I hope it helped!

**Comment by ajmajma** [comment]
@JPorry  Thanks for the response. Unfortunately, I have no choice in using a unique identifier because the information is coming from another team in my company and is not flexible. I'm sure more will run into this issue, maybe I should open a ticket to support track by $index? In the mean time I think I need to go with a different angular drag library, i have tested out  this one - https://github.com/marceljuenemann/angular-drag-and-drop-lists and it seems to support what I need. Thanks again!
