### ISSUE TITLE
Drag and drop have trembling with blocks of different size

### ISSUE THREAD

**Issue by ilyanaruson** [a5hik/ng-sortable#241]
Hello! 
Thank you for this plugin. 

There is one problem with drag and drop when you create blocks that have different sizes. Here is the copy of Plunker example you provide: http://plnkr.co/edit/EWqazPMfnUa12pR5lsjI?p=preview
There is one small change in this copy - third block is much bigger that another ones. You can see the bug if you drag  item1 and slowly move it over the big block. You can see annoying trembling.

Do you have any idea how this problem could be solved? 

Thanks in advance.

**Comment by MelanieMenard** [comment]
Hello,

just to say I am experiencing the same issue in my app and was about to raise a bug when I saw this one. I made a plunkr with my own CSS but the issue happens with the standard ul and li demo as demonstrated by the original reporter above.

http://plnkr.co/edit/OSEQbhT2zus9BlJQBBjY?p=preview

Many thanks for looking into the issue! This plugin is otherwise great so this flickering issue is a shame.

Kind regards.

**Comment by dizel3d** [comment]
@MelanieMenard, thank you! I have updated your example with actual master version to track a fix.

**Comment by ablamunits** [comment]
Hi,

I am experiencing this issue as well - it indeed seems that the problem occurs only when trying to drag a shorter element over a higher one.

Have there been any updates with this?

Cheers

**Comment by ilyanaruson** [comment]
@dizel3d thank you for the PR with fix!
