### ISSUE TITLE
Drag and drop doesn't work with IE9 

### ISSUE THREAD

**Issue by bagalekalyani** [a5hik/ng-sortable#262]
Drag and drop doesn't work with IE9, in the readme file it is mentioned that it supports IE9 and above versions but it dosent work in IE9. I tried opening github demo in IE9 but it dint work as expected.

**Comment by a5hik** [comment]
@bagalekalyani if is so.. then it might be broken with latest versions. let me check.

**Comment by marius-bughiu** [comment]
Same problem here in the latest version of IE. I suppose this is because PR #247 . 
If I undo the change in `dragStart` & call
`$helper.movePosition(eventObj, dragElement, itemPosition, containment, containerPositioning, scrollableContainer);`
after
`containment.append(dragElement);`
(just as it was before that PR) then it works again in IE.

**Comment by Pranay92** [comment]
+1 This is happening for me as well.
