### ISSUE TITLE
Drag offset misaligned when scrolled down a page

### ISSUE THREAD

**Issue by blakecallens** [a5hik/ng-sortable#69]
If a sortable item is below the fold of a page, the item moves no lower than the y position of the window height when dragging, so if you have a page taller than the window height the dragging item will be stuck above your mouse. The dragging logic still works in alignment with the mouse (the item will drop where the mouse is).

It looks like the offset of the item, while dragging, is not accounting the current scroll position of the page.

**Comment by neagle** [comment]
I've got problems when the page is scrolled, and setting `containerPositioning: 'relative'` doesn't seem to affect the behavior either way.

I've attached a .gif that shows sortable behavior working just fine until the window is resized, after which it's off from where it should be.

![ng-sortable-bug](https://cloud.githubusercontent.com/assets/176993/6276322/e79418b0-b853-11e4-9070-fd8e025ebe1a.gif)

**Comment by msieurtoph** [comment]
+1. 
It got the same issue ... and headaches by the way ;)

@neagle, it could help you. Here are what my investigations:

#### Using `containment` option.

The `containerPositioning` option does not work well (at least in my case, probably because I have some others markup with a `relative` positioning in my markup, I don't know).
Regarding to the code, the positioning of the drag item seems to be really complex (too much maybe?)

Anyway, the only way to make this work for me was to manually add the `position:relative` to my containers and forget about `containerPositioning`.

#### Without the `containement` option.

The drag item is added to the body and it almost works.

The thing was about the css height of the body. I had to change my `html, body {height:100%}` to `html{height:100%} body{min-height:100%}`.

With `body{height:100%}`, the body only expands to the window's height, even if the page is taller.
With `body{min-height:100%}`, the body expands **at least** to the window's height but can expand to the page's height if taller.

----

Finally, I think `containment` option is buggy (and makes the code too complex). The actual implementation is not generic enough and only works in few cases. Maybe, we should think different about this part and maybe refactoring.

I guess (it is just a guess) it would be simpler to systematically add element to body. It would be easier to position. 
And if needed, manage a `rect` restriction to avoid item to be drag outside of a given container. We also can make this container, or the body by default, scroll when approaching its borders.



Anyway, thanks for this excellent plugin, because, except in this particular case, it works really well...

**Comment by Jeevanandanj** [comment]
Did this issue is resolved??

**Comment by Jeevanandanj** [comment]
I can solve this issue using containment: ".board". But after setting this option, I've got like, the draggable item is moving down which is inversely working as mention in the bug.

**Comment by melamri** [comment]
Are there any updates on this issue?
