### ISSUE TITLE
Directive fails silently when debugging symbols disabled

### ISSUE THREAD

**Issue by kernel-io** [a5hik/ng-sortable#71]
The directive fails silently when used in a 1.3.x application that has debugging info disabled.

```javascript
angular.module('myapp').config(['$compileProvider', function ($compileProvider) {
  $compileProvider.debugInfoEnabled(false);
}]);
```
The above code will break drag, albeit silently.

Lines 758 - 762 seem to be the issue. 
```javascript
              targetScope = targetElement.scope();

              if (!targetScope || !targetScope.type) {
                return;
              }
```
as well as line 689
```javascript
sourceScope = elementClicked.scope();
```

**Comment by pcan** [comment]
I have just found the bug: the isDraggable() function calls the .scope() method [here](https://github.com/a5hik/ng-sortable/blob/master/source/sortable-item-handle.js#L196) on a jqLite object, that is supported only in debug mode. See [the docs](https://docs.angularjs.org/api/ng/function/angular.element) (under jqLite Extras section)

**Comment by Pickra** [comment]
Hey @kernel-io have you found a solution for this issue?

**Comment by pcan** [comment]
I think I have found a solution to this. It's a bit dirty, but we could keep working on it in order to refine the approach. 
0) disable debug symbols with $compileProvider.debugInfoEnabled(false);
1) Try to replace sourceScope = elementClicked.scope(); in isDraggable() with the following:
```javascript
sourceScope = elementClicked.data().$asSortableItemHandleController.scope;
```
2) Then, in dragMove() replace targetScope = targetElement.scope(); with the following:
```javascript
var asSortableItemController = targetElement.data().$asSortableItemController || targetElement.parent().data().$asSortableItemController;
if(asSortableItemController) {
    targetScope = asSortableItemController.scope; //was .scope();
}
```
Side note: the or operator shortcircuit seems to be necessary when the sortable item is a <tr>; in this case the controller is found on the parent element.
Let me now what you think, and in case this is good I'll issue a pull req.

**Comment by kernel-io** [comment]
that works here, I don't see any issue with it? :+1:

**Comment by a5hik** [comment]
the version 1.2.1 having a fix for this issue, hence closing.
